### ISSUE TITLE
Algolia - Error when no match found

### ISSUE THREAD

**Issue by fufroma** [mduplouy/silex-cops#33]
Hello,

Using cops e0685a270481b133dd394d28ab902cd7e54aa6b0 .

Algolia is enabled, indexed, and autocomplete is false.

If I search for a non-existing element (example: 'fldksmlfksdlmfksmldkfmsjgldfjghdlfgjlksdfglfdkjglfd'), I have a blank page and a PHP error in the logs
```
 PHP Fatal error:  Uncaught Error: Call to a member function getId() on null in /home/user/www/fqdn.url/app/src/Cops/Front/Controller/SearchController.php:137
Stack trace:
#0 /home/user/www/fqdn.url/app/src/Cops/Front/Controller/SearchController.php(84): Cops\\Front\\Controller\\SearchController->loadBooksOrRedirect(Object(Cops\\Core\\Application), 'dslkjfsdlkjsdjk...', 1, '25')
#1 [internal function]: Cops\\Front\\Controller\\SearchController->resultAction(Object(Cops\\Core\\Application), 'dslkjfsdlkjsdjk...', 1)
#2 /home/user/www/fqdn.url/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php(145): call_user_func_array(Array, Array)
#3 /home/user/www/fqdn.url/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php(66): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)
#4 /home/user/www/fqdn.url/vendor/silex/silex/src/Silex/Application.php(586): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object in /home/user/www/fqdn.url/app/src/Cops/Front/Controller/SearchController.php on line 137, referer: http://fqdn.url/user/fr/
```

**Comment by mduplouy** [comment]
Thank you for the report, i'm gonna fix this very quickly :)

**Comment by fufroma** [comment]
Algolia answer :
```
{
  "hits": [
  ],
  "nbHits": 0,
  "page": 0,
  "nbPages": 0,
  "hitsPerPage": 25,
  "processingTimeMS": 1,
  "query": "v clkmv nfmlkgjdflmkgjlf",
  "params": "attributesToRetrieve=%5B%22id%22%5D&ignorePlurals=1&page=0&hitsPerPage=25&query=v+clkmv+nfmlkgjdflmkgjlf"
}
```
